application: pfif-tools
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /validate
  static_files: static/validator.html
  upload: static/validator.html
- url: /diff
  static_files: static/diff.html
  upload: static/diff.html
- url: /.*
  script: controller.py
