application: pfif-tools
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /
  static_files: static/validator.html
  upload: static/validator.html
- url: /.*
  script: validator_controller.py
