#!/bin/bash
# Runs the lint script on every .py file in the app directory and test
# directories.

pushd "$(dirname $0)" >/dev/null && source common.sh && popd >/dev/null

$TOOLS_DIR/lint $APP_DIR/*.py $TESTS_DIR/*.py "$@"
