#!/bin/bash

pushd "$(dirname $0)" >/dev/null && source common.sh && popd >/dev/null

echo "Reminder: to test coverage, you must run tools/unit_tests --with-coverage"

# Run coverage testing on every python file in the root of the app directory.
# Give line numbers for missing coverage.
coverage report --show-missing --rcfile=$TOOLS_DIR/.coveragerc $APP_DIR/*.py
