#!/bin/bash
# From Google Person Finder: http://code.google.com/p/googlepersonfinder/

# use pylint to check the args.
# requires installing pylint http://www.logilab.org/project/pylint
# short form: easy_install pylint (may require root)
LINT=$(which pylint)
# Don't generate a full report; only display the issues
REPORTS="no"
# Indent two spaces, not four spaces
INDENT_STRING="  "
# Long method names are okay
METHOD_REGEX="[a-z_][a-z0-9_]+$"

if [ -z "$LINT" ]; then
  echo "pylint not found, please install."
  exit 1
fi

pushd "$(dirname $0)" >/dev/null && source common.sh && popd >/dev/null
${LINT} --reports=${REPORTS} "--indent-string=${INDENT_STRING}" \
  "--method-rgx=${METHOD_REGEX}" "$@"
